version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd packages/client
      - run: yarn install
      - run: ./node_modules/.bin/jest --config="jest.config.js" 

workflows:
  test:
    jobs:
      - test
