version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: yarn install
      - run: yarn workspace @ario/client lint
      - run: yarn workspace @ario/client test

workflows:
  test:
    jobs:
      - test
