version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd packages/client
      - run: yarn install
      - run: yarn test

workflows:
  test:
    jobs:
      - test
